MintNFT type
zksync-sdk/zksync-python pull request #20
Opened 2021-06-01 14:33 UTC by kugaudo

2021-06-14 12:48 UTC, StanislavBreadless reviewed
Will test it later

2021-06-14 12:48 UTC, StanislavBreadless commented on zksync_sdk/types/transactions.py
> +        return Decimal(amount)*Decimal(10).scaleb(-1)
the number of decimals for nft is always 0, e.g. the nft has no decimal points

2021-06-14 12:48 UTC, StanislavBreadless commented on .gitignore
> +.idea/
Nit: please add a newline at the end of file

2021-06-14 12:49 UTC, StanislavBreadless commented
Also please make sure that the CI passes

2021-06-22 17:23 UTC, ly0va commented on tests/test_wallet.py
> +    async def test_mint_nft(self):
what about `test_withdraw_nft`?

2021-06-22 17:23 UTC, ly0va commented on zksync_sdk/serializers.py
> +MAX_NUMBER_OF_TOKENS = 4294967295
Probably better to specify this explicitly as `2 ** 32 - 1`

2021-06-23 10:38 UTC, ly0va requested changes
Also, what about [full exit for NFT](https://github.com/matter-labs/zksync/blob/1387e44b22f794910867132b361ac12222691268/sdk/zksync.js/src/wallet.ts#L1388)?

2021-06-23 10:45 UTC, StanislavBreadless commented
> Also, what about [full exit for NFT](https://github.com/matter-labs/zksync/blob/1387e44b22f794910867132b361ac12222691268/sdk/zksync.js/src/wallet.ts#L1388)?

Good point! This method is not needed for initial development. We'll add this in the next iteration.

2021-06-23 11:02 UTC, kugaudo commented on tests/test_wallet.py
> +    async def test_mint_nft(self):
Working on it

2021-06-24 09:40 UTC, ly0va approved these changes

2021-06-24 09:40 UTC, merged